In [2]:
# NumPy – Day 1 Assignment 
# Topic: Introduction to NumPy

# Question 1: Student Marks Array 
# Create a NumPy array containing the marks of 10 students. 
# Marks: 78, 85, 90, 67, 88, 92, 75, 81, 69, 95 
# Display: 
# ● Complete array 
# ● Data type 
# ● Total number of elements 
import numpy as np
marks = np.array([78, 85, 90, 67, 88, 92, 75, 81, 69, 95])

print("Question1:")
print("Complete Array:",marks)
print("Data Type:", marks.dtype)
print("Total Number of Elements:", marks.size)
print("\n")

# Question 2: Employee IDs 
# Create a NumPy array of employee IDs: 101, 102, 103, 104, 105, 106 
# Display: 
# ● Array 
# ● Number of dimensions 
# ● Shape 

Employee_ID = np.array([101, 102, 103, 104, 105, 106])

print("Question2:")
print("Array:",Employee_ID)
print("Number of dimensions:",Employee_ID.ndim)
print("Shape:",Employee_ID.shape)
print("\n")

# # Question 3: College Students Data (2D Array) 
# # Create the following 2D array. 
# # 78 82 90 
# # 65 70 88 
# # 91 86 79 
# # Display: 
# # ● Complete array 
# # ● Shape 
# # ● Size 
# # ● Data type 

students = np.array([[78, 82, 90],
                     [65, 70, 88],
                     [91, 86, 79]])

print("Question3:")
print("Complete Array:")
print(students)
print("Shape:", students.shape)
print("Size:", students.size)
print("Data Type:", students.dtype)
print("\n")

# # Question 4: Zero Matrix 
# # Create a 5 × 5 Zero Matrix using NumPy. 
# # Display the matrix. 

print("Question4:")
zero_matrix = np.zeros((5,5))
print("Zeros Matrix:")
print(zero_matrix)
print("\n")

# # Question 5: Ones Matrix 
# # Create a 4 × 6 Ones Matrix using NumPy. 
# # Display the matrix. 

print("Question5:")
ones_matrix = np.ones((4,6))
print("Ones matrix:")
print(ones_matrix)
print("\n")
      
# # Question 6: Identity Matrix 
# # Create a 6 × 6 Identity Matrix using NumPy. 
# # Display the matrix. 

print("Question6:")
Identity_matrix = np.eye(6)
print("Identity Matrix:")
print(Identity_matrix)
print("\n")
 
# # Question 7: Full Matrix 
# # Create a 4 × 4 matrix in which every element is 25. 
# # Display the matrix. 

print("Question7:")
full_matrix = np.full((4, 4),25)
print("full_matrix:")
print(full_matrix)
print("\n")

# Question 8: arange() 
# Create the following arrays using np.arange() 
# Array 1 : 1 2 3 4 5 6 7 8 9 10 
# Array 2 : 10 20 30 40 50 60 70 80 90 100 
# Display both arrays. 

array1 = np.arange(1, 11)
array2 = np.arange(10, 101, 10)

print("Question8:")
print("Array 1:",array1)
print("Array 2:",array2)
print("\n")

# Question 9: linspace() 
# Create an array containing 8 equally spaced values between 0 and 100 using 
# np.linspace(). 
#Display the array.

print("Question9:")
array = np.linspace(0, 100, 8)
print(array)
print("\n")

# Question 10: Complete Array Properties 
# Create the following array. 
# 10 20 30 
# 40 50 60 
# 70 80 90 
# Display the following properties: 
# ● Number of Dimensions (ndim) 
# ● Shape (shape) 
# ● Size (size) 
# ● Data Type (dtype) 

data = np.array ([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])

print("Question10:")
print("Number of Dimensions:",data.ndim)
print("Shape:",data.shape)
print("Size:",data.size)
print("Data type:",data.dtype)
print("\n")

Question1:
Complete Array: [78 85 90 67 88 92 75 81 69 95]
Data Type: int64
Total Number of Elements: 10


Question2:
Array: [101 102 103 104 105 106]
Number of dimensions: 1
Shape: (6,)


Question3:
Complete Array:
[[78 82 90]
 [65 70 88]
 [91 86 79]]
Shape: (3, 3)
Size: 9
Data Type: int64


Question4:
Zeros Matrix:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Question5:
Ones matrix:
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


Question6:
Identity Matrix:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


Question7:
full_matrix:
[[25 25 25 25]
 [25 25 25 25]
 [25 25 25 25]
 [25 25 25 25]]


Question8:
Array 1: [ 1  2  3  4  5  6  7  8  9 10]
Array 2: [ 10  20  30  40  50  60  70  80  90 100]


Question9:
[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


Question